# Generated by Django 5.0.2 on 2026-01-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_financialtransaction_message_notice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('bimestral', 'Bimestral'), ('trimestral', 'Trimestral')], default='bimestral', max_length=20)),
                ('calculation_method', models.CharField(choices=[('arithmetic', 'Media aritmetica'), ('weighted', 'Media ponderada')], default='arithmetic', max_length=20)),
                ('min_passing_grade', models.DecimalField(decimal_places=2, default=6, max_digits=5)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('recovery_rule', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
    ]
