# Generated by Django 5.0.2 on 2026-01-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auditlog_uploadattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.invoice'),
        ),
    ]
