# Generated by Django 5.1.5 on 2026-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_student'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='api_passwor_user_id_8e1682_idx',
            old_name='api_passwor_user_id_50c6d2_idx',
        ),
        migrations.AddField(
            model_name='school',
            name='payment_gateway',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(blank=True, default='#4F46E5', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('director', 'Diretor'), ('coordinator', 'Coordenador'), ('teacher', 'Professor'), ('student', 'Aluno'), ('staff', 'Equipe'), ('finance', 'Financeiro'), ('support', 'Suporte')], default='staff', max_length=20),
        ),
    ]
