# Generated by Django 5.1.5 on 2026-01-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_school_institution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.CharField(blank=True, help_text='URL or path to logo', max_length=500, null=True),
        ),
    ]
