# Generated by Django 5.1.5 on 2026-01-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_school_logo'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_school DROP COLUMN IF EXISTS logo_url;",
            reverse_sql="ALTER TABLE api_school ADD COLUMN logo_url varchar(200) DEFAULT NULL;"
        )
    ]
