# Generated by Django 5.1.5 on 2026-01-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_drop_stale_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadattachment',
            name='entity_type',
            field=models.CharField(choices=[('material', 'Material'), ('justification', 'Justificativa'), ('exam', 'Prova'), ('message', 'Mensagem'), ('school_logo', 'Logo da Escola')], max_length=30),
        ),
    ]
