# Generated by Django 5.1.5 on 2026-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_lessonplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
