from django.urls import path

from . import views

urlpatterns = [
    path("auth/register/", views.register_user, name="register_user"),
    path("auth/login/", views.login_user, name="login_user"),
    path("auth/logout/", views.logout_user, name="logout_user"),
    path("auth/refresh/", views.refresh_token, name="refresh_token"),
    path("auth/revoke/", views.revoke_token, name="revoke_token"),
    path("auth/me/", views.get_me, name="get_me"),
    path("users/", views.users, name="users"),
    path("users/<int:user_id>/", views.user_detail, name="user_detail"),
    path("staff/", views.staff, name="staff"),
    path("staff/<int:staff_id>/", views.staff_detail, name="staff_detail"),
    path("schools/", views.schools, name="schools"),
    path("schools/<int:school_id>/", views.school_detail, name="school_detail"),
    path("classrooms/", views.classrooms, name="classrooms"),
    path("classrooms/<int:classroom_id>/", views.classroom_detail, name="classroom_detail"),
    path(
        "classrooms/<int:classroom_id>/allocations/",
        views.classroom_allocations,
        name="classroom_allocations",
    ),
    path(
        "classrooms/<int:classroom_id>/students/",
        views.classroom_students,
        name="classroom_students",
    ),
    path("students/", views.students, name="students"),
    path("students/<int:student_id>/", views.student_detail, name="student_detail"),
    path(
        "students/<int:student_id>/contacts/",
        views.student_contacts,
        name="student_contacts",
    ),
    path(
        "students/<int:student_id>/parents/",
        views.student_parents,
        name="student_parents",
    ),
    path(
        "contacts/<int:contact_id>/",
        views.emergency_contact_detail,
        name="emergency_contact_detail",
    ),
    path("guardians/", views.guardians, name="guardians"),
    path("guardians/<int:guardian_id>/", views.guardian_detail, name="guardian_detail"),
    path("student-guardians/", views.student_guardian_link, name="student_guardian_link"),
    path("enrollments/", views.enrollments, name="enrollments"),
    path("enrollments/<int:enrollment_id>/", views.enrollment_detail, name="enrollment_detail"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoices/<int:invoice_id>/", views.invoice_detail, name="invoice_detail"),
    path("grades/", views.grades, name="grades"),
    path("grades/<int:grade_id>/", views.grade_detail, name="grade_detail"),
    path("uploads/", views.uploads, name="uploads"),
    path("uploads/<int:upload_id>/", views.upload_detail, name="upload_detail"),
    path("audit-logs/", views.audit_logs, name="audit_logs"),
    path("cashflow/", views.cashflow_summary, name="cashflow_summary"),
    path("invoices/reconcile/", views.reconcile_invoices, name="reconcile_invoices"),
    path("attendance/", views.attendance, name="attendance"),
    path("attendance/<int:attendance_id>/", views.attendance_detail, name="attendance_detail"),
    path("diary-entries/", views.diary_entries, name="diary_entries"),
    path("diary-entries/<int:diary_id>/", views.diary_entry_detail, name="diary_entry_detail"),
    path("materials/", views.materials, name="materials"),
    path("materials/<int:material_id>/", views.material_detail, name="material_detail"),
    path("syllabi/", views.syllabi, name="syllabi"),
    path("syllabi/<int:syllabus_id>/", views.syllabus_detail, name="syllabus_detail"),
    path("transactions/", views.transactions, name="transactions"),
    path("transactions/<int:transaction_id>/", views.transaction_detail, name="transaction_detail"),
    path("notices/", views.notices, name="notices"),
    path("notices/<int:notice_id>/", views.notice_detail, name="notice_detail"),
    path("conversations/", views.conversations, name="conversations"),
    path(
        "conversations/<int:conversation_id>/messages/",
        views.conversation_messages,
        name="conversation_messages",
    ),
    path("time-slots/", views.time_slots, name="time_slots"),
    path("time-slots/<int:slot_id>/", views.time_slot_detail, name="time_slot_detail"),
    path("availability/", views.availability, name="availability"),
    path(
        "availability/<int:availability_id>/",
        views.availability_detail,
        name="availability_detail",
    ),
    path("schedules/", views.schedules, name="schedules"),
    path("schedules/<int:schedule_id>/", views.schedule_detail, name="schedule_detail"),
    path("teachers/<int:teacher_id>/schedule/", views.teacher_schedule, name="teacher_schedule"),
    path("grading-config/", views.grading_config, name="grading_config"),
    path("insights/", views.generate_insight, name="generate_insight"),
    path("lesson-plans/", views.generate_lesson_plan, name="generate_lesson_plan"),
    path("financial-health/", views.analyze_financial_health, name="analyze_financial_health"),
    path("school-documents/", views.generate_school_document, name="generate_school_document"),
]
